//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanSat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CanSat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Botao_fechar {
            get {
                object obj = ResourceManager.GetObject("Botao_fechar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Botão_gráfico_desabilitado {
            get {
                object obj = ResourceManager.GetObject("Botão_gráfico_desabilitado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Botão_habilitado_Quit {
            get {
                object obj = ResourceManager.GetObject("Botão_habilitado_Quit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Botão_home_desabilitado {
            get {
                object obj = ResourceManager.GetObject("Botão_home_desabilitado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Botão_log_desabilitado {
            get {
                object obj = ResourceManager.GetObject("Botão_log_desabilitado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Botão_mapa_desabilitado {
            get {
                object obj = ResourceManager.GetObject("Botão_mapa_desabilitado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Botão_menu_inicial_armazenamento_habilitado {
            get {
                object obj = ResourceManager.GetObject("Botão_menu_inicial_armazenamento_habilitado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Botão_menu_inicial_conexão_habilitado {
            get {
                object obj = ResourceManager.GetObject("Botão_menu_inicial_conexão_habilitado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Botão_menu_inicial_execução_habilitado {
            get {
                object obj = ResourceManager.GetObject("Botão_menu_inicial_execução_habilitado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Botao_minimizar {
            get {
                object obj = ResourceManager.GetObject("Botao_minimizar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Botão_ok_habilitado_grande {
            get {
                object obj = ResourceManager.GetObject("Botão_ok_habilitado_grande", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Botão_ok_habilitado_pequeno {
            get {
                object obj = ResourceManager.GetObject("Botão_ok_habilitado_pequeno", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Conectado_com_sucesso {
            get {
                object obj = ResourceManager.GetObject("Conectado_com_sucesso", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Conectando {
            get {
                object obj = ResourceManager.GetObject("Conectando", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Deseja_sair {
            get {
                object obj = ResourceManager.GetObject("Deseja_sair", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estabelece a conexão via USB.
        /// </summary>
        internal static string dicaPC1 {
            get {
                return ResourceManager.GetString("dicaPC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estabelece a conexão via WiFi.
        /// </summary>
        internal static string dicaPC2 {
            get {
                return ResourceManager.GetString("dicaPC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:8080/Canastra/Teste.html.
        /// </summary>
        internal static string enderecoMapa {
            get {
                return ResourceManager.GetString("enderecoMapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Erro_ao_conectar {
            get {
                object obj = ResourceManager.GetObject("Erro_ao_conectar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Erro_dispositivo_removivel {
            get {
                object obj = ResourceManager.GetObject("Erro_dispositivo_removivel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar se conectar à porta.
        /// </summary>
        internal static string erroPortaSerial {
            get {
                return ResourceManager.GetString("erroPortaSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grafico_pic0 {
            get {
                object obj = ResourceManager.GetObject("grafico_pic0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grafico_pic1 {
            get {
                object obj = ResourceManager.GetObject("grafico_pic1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grafico_pic2 {
            get {
                object obj = ResourceManager.GetObject("grafico_pic2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grafico_pic3 {
            get {
                object obj = ResourceManager.GetObject("grafico_pic3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grafico_pic4 {
            get {
                object obj = ResourceManager.GetObject("grafico_pic4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grafico_pic5 {
            get {
                object obj = ResourceManager.GetObject("grafico_pic5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grafico_pic6 {
            get {
                object obj = ResourceManager.GetObject("grafico_pic6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grafico_pic7 {
            get {
                object obj = ResourceManager.GetObject("grafico_pic7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grafico_pic8 {
            get {
                object obj = ResourceManager.GetObject("grafico_pic8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo (s).
        /// </summary>
        internal static string grafico_x0 {
            get {
                return ResourceManager.GetString("grafico_x0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo (s).
        /// </summary>
        internal static string grafico_x1 {
            get {
                return ResourceManager.GetString("grafico_x1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo (s).
        /// </summary>
        internal static string grafico_x2 {
            get {
                return ResourceManager.GetString("grafico_x2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo (s).
        /// </summary>
        internal static string grafico_x3 {
            get {
                return ResourceManager.GetString("grafico_x3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude (m).
        /// </summary>
        internal static string grafico_x4 {
            get {
                return ResourceManager.GetString("grafico_x4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo (s).
        /// </summary>
        internal static string grafico_x5 {
            get {
                return ResourceManager.GetString("grafico_x5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude (m).
        /// </summary>
        internal static string grafico_x6 {
            get {
                return ResourceManager.GetString("grafico_x6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo (s).
        /// </summary>
        internal static string grafico_x7 {
            get {
                return ResourceManager.GetString("grafico_x7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude (m).
        /// </summary>
        internal static string grafico_x8 {
            get {
                return ResourceManager.GetString("grafico_x8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distância (m).
        /// </summary>
        internal static string grafico_y0 {
            get {
                return ResourceManager.GetString("grafico_y0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocidade (m/s).
        /// </summary>
        internal static string grafico_y1 {
            get {
                return ResourceManager.GetString("grafico_y1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceleração (m/s²).
        /// </summary>
        internal static string grafico_y2 {
            get {
                return ResourceManager.GetString("grafico_y2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressão (KPa).
        /// </summary>
        internal static string grafico_y3 {
            get {
                return ResourceManager.GetString("grafico_y3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressão (KPa).
        /// </summary>
        internal static string grafico_y4 {
            get {
                return ResourceManager.GetString("grafico_y4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperatura (ºC).
        /// </summary>
        internal static string grafico_y5 {
            get {
                return ResourceManager.GetString("grafico_y5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperatura (ºC).
        /// </summary>
        internal static string grafico_y6 {
            get {
                return ResourceManager.GetString("grafico_y6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luminosidade (lux).
        /// </summary>
        internal static string grafico_y7 {
            get {
                return ResourceManager.GetString("grafico_y7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luminosidade (lux).
        /// </summary>
        internal static string grafico_y8 {
            get {
                return ResourceManager.GetString("grafico_y8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconeCanastra {
            get {
                object obj = ResourceManager.GetObject("IconeCanastra", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Janela_armazenamento {
            get {
                object obj = ResourceManager.GetObject("Janela_armazenamento", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Janela_conexão {
            get {
                object obj = ResourceManager.GetObject("Janela_conexão", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Janela_execução {
            get {
                object obj = ResourceManager.GetObject("Janela_execução", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files\Google\Chrome\Application\chrome.exe.
        /// </summary>
        internal static string localChrome {
            get {
                return ResourceManager.GetString("localChrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar se conectar.
        /// </summary>
        internal static string logConexaoFalha {
            get {
                return ResourceManager.GetString("logConexaoFalha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conectado com êxito via Serial.
        /// </summary>
        internal static string logConexaoSerial {
            get {
                return ResourceManager.GetString("logConexaoSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conectado com êxito via WiFi.
        /// </summary>
        internal static string logConexaoWifi {
            get {
                return ResourceManager.GetString("logConexaoWifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.txt.
        /// </summary>
        internal static string logFile {
            get {
                return ResourceManager.GetString("logFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Menu_Inicial {
            get {
                object obj = ResourceManager.GetObject("Menu_Inicial", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, selecione um dispositivo removível..
        /// </summary>
        internal static string msgSelRemovivel {
            get {
                return ResourceManager.GetString("msgSelRemovivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cansat Registros.
        /// </summary>
        internal static string pastaLocal {
            get {
                return ResourceManager.GetString("pastaLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Splashscreen {
            get {
                object obj = ResourceManager.GetObject("Splashscreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
