//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanSat.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CanSat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Botao_fechar {
            get {
                object obj = ResourceManager.GetObject("Botao_fechar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Botão_gráfico_desabilitado {
            get {
                object obj = ResourceManager.GetObject("Botão_gráfico_desabilitado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Botão_habilitado_Quit {
            get {
                object obj = ResourceManager.GetObject("Botão_habilitado_Quit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Botão_home_desabilitado {
            get {
                object obj = ResourceManager.GetObject("Botão_home_desabilitado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Botão_log_desabilitado {
            get {
                object obj = ResourceManager.GetObject("Botão_log_desabilitado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Botão_mapa_desabilitado {
            get {
                object obj = ResourceManager.GetObject("Botão_mapa_desabilitado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Botão_menu_inicial_armazenamento_habilitado {
            get {
                object obj = ResourceManager.GetObject("Botão_menu_inicial_armazenamento_habilitado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Botão_menu_inicial_conexão_habilitado {
            get {
                object obj = ResourceManager.GetObject("Botão_menu_inicial_conexão_habilitado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Botão_menu_inicial_execução_habilitado {
            get {
                object obj = ResourceManager.GetObject("Botão_menu_inicial_execução_habilitado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Botao_minimizar {
            get {
                object obj = ResourceManager.GetObject("Botao_minimizar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Botão_ok_habilitado_grande {
            get {
                object obj = ResourceManager.GetObject("Botão_ok_habilitado_grande", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Botão_ok_habilitado_pequeno {
            get {
                object obj = ResourceManager.GetObject("Botão_ok_habilitado_pequeno", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Conectado_com_sucesso {
            get {
                object obj = ResourceManager.GetObject("Conectado_com_sucesso", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Conectando {
            get {
                object obj = ResourceManager.GetObject("Conectando", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Deseja_sair {
            get {
                object obj = ResourceManager.GetObject("Deseja_sair", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estabelece a conexão via USB.
        /// </summary>
        internal static string dicaPC1 {
            get {
                return ResourceManager.GetString("dicaPC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estabelece a conexão via WiFi.
        /// </summary>
        internal static string dicaPC2 {
            get {
                return ResourceManager.GetString("dicaPC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a http://localhost:80/Database-Canastra/Teste.html.
        /// </summary>
        internal static string enderecoMapa {
            get {
                return ResourceManager.GetString("enderecoMapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Erro_ao_conectar {
            get {
                object obj = ResourceManager.GetObject("Erro_ao_conectar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Erro_dispositivo_removivel {
            get {
                object obj = ResourceManager.GetObject("Erro_dispositivo_removivel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao tentar se conectar à porta.
        /// </summary>
        internal static string erroPortaSerial {
            get {
                return ResourceManager.GetString("erroPortaSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grafico_pic0 {
            get {
                object obj = ResourceManager.GetObject("grafico_pic0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grafico_pic1 {
            get {
                object obj = ResourceManager.GetObject("grafico_pic1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grafico_pic2 {
            get {
                object obj = ResourceManager.GetObject("grafico_pic2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grafico_pic3 {
            get {
                object obj = ResourceManager.GetObject("grafico_pic3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grafico_pic4 {
            get {
                object obj = ResourceManager.GetObject("grafico_pic4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grafico_pic5 {
            get {
                object obj = ResourceManager.GetObject("grafico_pic5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grafico_pic6 {
            get {
                object obj = ResourceManager.GetObject("grafico_pic6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grafico_pic7 {
            get {
                object obj = ResourceManager.GetObject("grafico_pic7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grafico_pic8 {
            get {
                object obj = ResourceManager.GetObject("grafico_pic8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tempo (s).
        /// </summary>
        internal static string grafico_x0 {
            get {
                return ResourceManager.GetString("grafico_x0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tempo (s).
        /// </summary>
        internal static string grafico_x1 {
            get {
                return ResourceManager.GetString("grafico_x1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tempo (s).
        /// </summary>
        internal static string grafico_x2 {
            get {
                return ResourceManager.GetString("grafico_x2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tempo (s).
        /// </summary>
        internal static string grafico_x3 {
            get {
                return ResourceManager.GetString("grafico_x3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Altitude (m).
        /// </summary>
        internal static string grafico_x4 {
            get {
                return ResourceManager.GetString("grafico_x4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tempo (s).
        /// </summary>
        internal static string grafico_x5 {
            get {
                return ResourceManager.GetString("grafico_x5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Altitude (m).
        /// </summary>
        internal static string grafico_x6 {
            get {
                return ResourceManager.GetString("grafico_x6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tempo (s).
        /// </summary>
        internal static string grafico_x7 {
            get {
                return ResourceManager.GetString("grafico_x7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Altitude (m).
        /// </summary>
        internal static string grafico_x8 {
            get {
                return ResourceManager.GetString("grafico_x8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Distância (m).
        /// </summary>
        internal static string grafico_y0 {
            get {
                return ResourceManager.GetString("grafico_y0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Velocidade (m/s).
        /// </summary>
        internal static string grafico_y1 {
            get {
                return ResourceManager.GetString("grafico_y1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aceleração (m/s²).
        /// </summary>
        internal static string grafico_y2 {
            get {
                return ResourceManager.GetString("grafico_y2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pressão (KPa).
        /// </summary>
        internal static string grafico_y3 {
            get {
                return ResourceManager.GetString("grafico_y3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pressão (KPa).
        /// </summary>
        internal static string grafico_y4 {
            get {
                return ResourceManager.GetString("grafico_y4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Temperatura (ºC).
        /// </summary>
        internal static string grafico_y5 {
            get {
                return ResourceManager.GetString("grafico_y5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Temperatura (ºC).
        /// </summary>
        internal static string grafico_y6 {
            get {
                return ResourceManager.GetString("grafico_y6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Luminosidade (lux).
        /// </summary>
        internal static string grafico_y7 {
            get {
                return ResourceManager.GetString("grafico_y7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Luminosidade (lux).
        /// </summary>
        internal static string grafico_y8 {
            get {
                return ResourceManager.GetString("grafico_y8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Icon semelhante a (Ícone).
        /// </summary>
        internal static System.Drawing.Icon IconeCanastra {
            get {
                object obj = ResourceManager.GetObject("IconeCanastra", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Janela_armazenamento {
            get {
                object obj = ResourceManager.GetObject("Janela_armazenamento", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Janela_conexão {
            get {
                object obj = ResourceManager.GetObject("Janela_conexão", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Janela_execução {
            get {
                object obj = ResourceManager.GetObject("Janela_execução", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C:\Program Files (x86)\Google\Chrome\Application\chrome.exe.
        /// </summary>
        internal static string localChrome {
            get {
                return ResourceManager.GetString("localChrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao tentar se conectar.
        /// </summary>
        internal static string logConexaoFalha {
            get {
                return ResourceManager.GetString("logConexaoFalha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conectado com êxito via Serial.
        /// </summary>
        internal static string logConexaoSerial {
            get {
                return ResourceManager.GetString("logConexaoSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conectado com êxito via WiFi.
        /// </summary>
        internal static string logConexaoWifi {
            get {
                return ResourceManager.GetString("logConexaoWifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Log.txt.
        /// </summary>
        internal static string logFile {
            get {
                return ResourceManager.GetString("logFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mapa {
            get {
                object obj = ResourceManager.GetObject("mapa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Menu_Inicial {
            get {
                object obj = ResourceManager.GetObject("Menu_Inicial", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor, selecione um dispositivo removível..
        /// </summary>
        internal static string msgSelRemovivel {
            get {
                return ResourceManager.GetString("msgSelRemovivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cansat Registros.
        /// </summary>
        internal static string pastaLocal {
            get {
                return ResourceManager.GetString("pastaLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Splashscreen {
            get {
                object obj = ResourceManager.GetObject("Splashscreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
